# Site Settings
title                    : "Rowan's Blog"
title_separator          : "-"
subtitle                 : "记录想法、观察世界与自我成长"
name                     : "Rowan"
description              : "记录想法、观察世界与自我成长"
url                      : "https://loverose0211.github.io"  # 替换为你的实际URL
baseurl                  : ""
repository               : "loverose0211/loverose0211.github.io"  # 替换为你的实际仓库

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Rowan"
  avatar           : # "/assets/images/bio-photo.jpg"  # 如果没有头像就注释掉
  bio              : "一个正在学习计算机科学的高中生"
  location         : "Somewhere"
  email            :
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/loverose0211"  # 替换为你的GitHub链接

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai  # 设置为中国时区

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
