# Site Settings
title                    : "Rowan's Blog"
title_separator          : "-"
subtitle                 : "记录想法、观察世界与自我成长"
name                     : "Rowan"
description              : "CS和自动化爱好者的成长记录"
url                      : "https://loverose0211.github.io"
baseurl                  : ""
repository               : "loverose0211/loverose0211.github.io"

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"  # 使用对比度更好的主题

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name             : "Rowan"
  avatar           : # "/assets/images/bio-photo.jpg"
  bio              : "一个CS和自动化的爱好者"
  location         : "Somewhere"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/loverose0211"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Search
search: true
search_full_content: true

# Comments (可选)
comments:
  provider: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      toc: true
      toc_label: "目录"
      toc_icon: "cog"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 中文字体优化
typography:
  font_family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif
